version: "3.3"
services:
    api:
        build:
            context: .
        ports:
            - "8000:8000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - '80:80'
            - '443:443'
        
